In [15]:
import numpy as np

In [16]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [17]:
x= np.array([2,3,5,6,8,9,3,5,9])
print(x)
print('total element => ',x.size)
print('dimension wise elements =>' ,x.shape)
print('dimention count =>',x.ndim)


[2 3 5 6 8 9 3 5 9]
total element =>  9
dimension wise elements => (9,)
dimention count => 1


In [18]:
y= np.array([[2,3,5],[3,4,5]])
print(y)
print('total element => ',y.size)
print('dimension wise elements =>' ,y.shape)
print('dimention count =>',y.ndim)

[[2 3 5]
 [3 4 5]]
total element =>  6
dimension wise elements => (2, 3)
dimention count => 2


In [20]:
z= np.array([[2,3,5],[3,4,5],[1,2,3]])
print(z)
print('total element => ',z.size)
print('dimension wise elements =>' ,z.shape)
print('dimention count =>',z.ndim)

[[2 3 5]
 [3 4 5]
 [1 2 3]]
total element =>  9
dimension wise elements => (3, 3)
dimention count => 2


In [22]:
x=[1,3,5,7,9]
z=np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape',z.shape)
print(z)
print('dimention count =>',z.ndim)
print('total element => ',z.size)

shape (3, 3, 5)
[[[1 3 5 7 9]
  [1 3 5 7 9]
  [1 3 5 7 9]]

 [[1 3 5 7 9]
  [1 3 5 7 9]
  [1 3 5 7 9]]

 [[1 3 5 7 9]
  [1 3 5 7 9]
  [1 3 5 7 9]]]
dimention count => 3
total element =>  45


In [26]:
x=[1,3,5,2,4,6,7,8,9,1]
z=np.array([x,x,x,x,x,x,x,x,x,x])
print('shape',z.shape)
print(z)
print('dimention count =>',z.ndim)
print('total element => ',z.size)

shape (10, 10)
[[1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]
 [1 3 5 2 4 6 7 8 9 1]]
dimention count => 2
total element =>  100


In [29]:
d=np.arange(-10,11,.5)
d.shape


(42,)

In [30]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [31]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [34]:
a=np.linspace(1,1000,11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [47]:
d=np.random.randint(1,6,(10,10))
print(d)

[[3 4 2 3 2 4 4 5 5 4]
 [5 1 3 1 3 1 1 3 3 1]
 [2 3 3 4 3 2 1 4 2 1]
 [2 1 1 4 4 4 5 2 5 2]
 [2 1 5 3 1 4 1 1 5 4]
 [1 5 4 1 1 5 1 4 3 2]
 [1 2 4 4 5 5 4 3 2 2]
 [3 4 5 5 4 1 3 1 1 5]
 [4 3 5 2 2 4 3 1 4 4]
 [5 4 4 2 1 2 5 3 4 1]]


In [49]:
d[0]

array([3, 4, 2, 3, 2, 4, 4, 5, 5, 4])

In [50]:
d[0,0] #d[0][0]

3

In [51]:
d[3][5] #d[3,5]

4

In [53]:
d[:,0] #all rows of column idx 0

array([3, 5, 2, 2, 2, 1, 1, 3, 4, 5])

In [54]:
d[:5,2] # first five rows of column idx 2

array([2, 3, 3, 1, 5])

In [80]:
d[-1,5:]

array([2, 5, 3, 4, 1])

In [56]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x,'\n',y)

[[2 1 7]
 [8 5 4]
 [9 2 3]] 
 [[5 4 9]
 [6 7 8]
 [7 2 4]]


In [57]:
x+y

array([[ 7,  5, 16],
       [14, 12, 12],
       [16,  4,  7]])

In [58]:
x-y

array([[-3, -3, -2],
       [ 2, -2, -4],
       [ 2,  0, -1]])

In [59]:
x*y

array([[10,  4, 63],
       [48, 35, 32],
       [63,  4, 12]])

In [60]:
x/y

array([[0.4       , 0.25      , 0.77777778],
       [1.33333333, 0.71428571, 0.5       ],
       [1.28571429, 1.        , 0.75      ]])

In [61]:
x+10

array([[12, 11, 17],
       [18, 15, 14],
       [19, 12, 13]])

In [62]:
x*10

array([[20, 10, 70],
       [80, 50, 40],
       [90, 20, 30]])

In [63]:
x -10

array([[-8, -9, -3],
       [-2, -5, -6],
       [-1, -8, -7]])

In [64]:
np.dot(x,y)

array([[ 65,  29,  54],
       [ 98,  75, 128],
       [ 78,  56, 109]])

In [65]:
np.matmul(x,y)

array([[ 65,  29,  54],
       [ 98,  75, 128],
       [ 78,  56, 109]])

In [66]:
np.multiply(x,y)

array([[10,  4, 63],
       [48, 35, 32],
       [63,  4, 12]])

In [67]:
np.cross(x,y)

array([[-19,  17,   3],
       [ 12, -40,  26],
       [  2, -15,   4]])

In [68]:
np.hstack([x,y])

array([[2, 1, 7, 5, 4, 9],
       [8, 5, 4, 6, 7, 8],
       [9, 2, 3, 7, 2, 4]])

In [70]:
np.vstack([x,y])

array([[2, 1, 7],
       [8, 5, 4],
       [9, 2, 3],
       [5, 4, 9],
       [6, 7, 8],
       [7, 2, 4]])

In [71]:
np.append(x,y,axis=0)

array([[2, 1, 7],
       [8, 5, 4],
       [9, 2, 3],
       [5, 4, 9],
       [6, 7, 8],
       [7, 2, 4]])

In [72]:
x.max()

9

In [73]:
x.max(axis=0)

array([9, 5, 7])

In [74]:
x.min(axis=1)

array([1, 4, 2])

In [76]:
x.flatten()

array([2, 1, 7, 8, 5, 4, 9, 2, 3])

In [77]:
d[d>3]#boolean filter

array([4, 4, 4, 5, 5, 4, 5, 4, 4, 4, 4, 4, 5, 5, 5, 4, 5, 4, 5, 4, 5, 4,
       4, 4, 5, 5, 4, 4, 5, 5, 4, 5, 4, 5, 4, 4, 4, 5, 4, 4, 5, 4])

In [78]:
d[d==1] #give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])